# Generated by Django 5.0.7 on 2024-08-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agency',
            new_name='agency_id',
        ),
    ]
